package io.akhilennu.chatbot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BotTrainingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotTrainingAllPropertiesEquals(BotTraining expected, BotTraining actual) {
        assertBotTrainingAutoGeneratedPropertiesEquals(expected, actual);
        assertBotTrainingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotTrainingAllUpdatablePropertiesEquals(BotTraining expected, BotTraining actual) {
        assertBotTrainingUpdatableFieldsEquals(expected, actual);
        assertBotTrainingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotTrainingAutoGeneratedPropertiesEquals(BotTraining expected, BotTraining actual) {
        assertThat(actual)
            .as("Verify BotTraining auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotTrainingUpdatableFieldsEquals(BotTraining expected, BotTraining actual) {
        assertThat(actual)
            .as("Verify BotTraining relevant properties")
            .satisfies(a -> assertThat(a.getTrainingTime()).as("check trainingTime").isEqualTo(expected.getTrainingTime()))
            .satisfies(a -> assertThat(a.getAccuracy()).as("check accuracy").isEqualTo(expected.getAccuracy()))
            .satisfies(a -> assertThat(a.getPrecision()).as("check precision").isEqualTo(expected.getPrecision()))
            .satisfies(a -> assertThat(a.getf1Score()).as("check f1Score").isEqualTo(expected.getf1Score()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotTrainingUpdatableRelationshipsEquals(BotTraining expected, BotTraining actual) {
        assertThat(actual)
            .as("Verify BotTraining relationships")
            .satisfies(a -> assertThat(a.getBot()).as("check bot").isEqualTo(expected.getBot()));
    }
}
