package io.akhilennu.chatbot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConversationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationAllPropertiesEquals(Conversation expected, Conversation actual) {
        assertConversationAutoGeneratedPropertiesEquals(expected, actual);
        assertConversationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationAllUpdatablePropertiesEquals(Conversation expected, Conversation actual) {
        assertConversationUpdatableFieldsEquals(expected, actual);
        assertConversationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationAutoGeneratedPropertiesEquals(Conversation expected, Conversation actual) {
        assertThat(actual)
            .as("Verify Conversation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationUpdatableFieldsEquals(Conversation expected, Conversation actual) {
        assertThat(actual)
            .as("Verify Conversation relevant properties")
            .satisfies(a -> assertThat(a.getConversationId()).as("check conversationId").isEqualTo(expected.getConversationId()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getChannelName()).as("check channelName").isEqualTo(expected.getChannelName()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationUpdatableRelationshipsEquals(Conversation expected, Conversation actual) {
        // empty method
    }
}
