package io.akhilennu.chatbot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResponseDataAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponseDataAllPropertiesEquals(ResponseData expected, ResponseData actual) {
        assertResponseDataAutoGeneratedPropertiesEquals(expected, actual);
        assertResponseDataAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponseDataAllUpdatablePropertiesEquals(ResponseData expected, ResponseData actual) {
        assertResponseDataUpdatableFieldsEquals(expected, actual);
        assertResponseDataUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponseDataAutoGeneratedPropertiesEquals(ResponseData expected, ResponseData actual) {
        assertThat(actual)
            .as("Verify ResponseData auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponseDataUpdatableFieldsEquals(ResponseData expected, ResponseData actual) {
        assertThat(actual)
            .as("Verify ResponseData relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getChannelName()).as("check channelName").isEqualTo(expected.getChannelName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResponseDataUpdatableRelationshipsEquals(ResponseData expected, ResponseData actual) {
        // empty method
    }
}
