package io.akhilennu.chatbot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SlotValueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotValueAllPropertiesEquals(SlotValue expected, SlotValue actual) {
        assertSlotValueAutoGeneratedPropertiesEquals(expected, actual);
        assertSlotValueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotValueAllUpdatablePropertiesEquals(SlotValue expected, SlotValue actual) {
        assertSlotValueUpdatableFieldsEquals(expected, actual);
        assertSlotValueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotValueAutoGeneratedPropertiesEquals(SlotValue expected, SlotValue actual) {
        assertThat(actual)
            .as("Verify SlotValue auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotValueUpdatableFieldsEquals(SlotValue expected, SlotValue actual) {
        assertThat(actual)
            .as("Verify SlotValue relevant properties")
            .satisfies(a -> assertThat(a.getSlotName()).as("check slotName").isEqualTo(expected.getSlotName()))
            .satisfies(a -> assertThat(a.getSlotValue()).as("check slotValue").isEqualTo(expected.getSlotValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotValueUpdatableRelationshipsEquals(SlotValue expected, SlotValue actual) {
        assertThat(actual)
            .as("Verify SlotValue relationships")
            .satisfies(a -> assertThat(a.getConversation()).as("check conversation").isEqualTo(expected.getConversation()));
    }
}
