package io.akhilennu.chatbot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UtteranceIntentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtteranceIntentAllPropertiesEquals(UtteranceIntent expected, UtteranceIntent actual) {
        assertUtteranceIntentAutoGeneratedPropertiesEquals(expected, actual);
        assertUtteranceIntentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtteranceIntentAllUpdatablePropertiesEquals(UtteranceIntent expected, UtteranceIntent actual) {
        assertUtteranceIntentUpdatableFieldsEquals(expected, actual);
        assertUtteranceIntentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtteranceIntentAutoGeneratedPropertiesEquals(UtteranceIntent expected, UtteranceIntent actual) {
        assertThat(actual)
            .as("Verify UtteranceIntent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtteranceIntentUpdatableFieldsEquals(UtteranceIntent expected, UtteranceIntent actual) {
        assertThat(actual)
            .as("Verify UtteranceIntent relevant properties")
            .satisfies(a -> assertThat(a.getStartIndex()).as("check startIndex").isEqualTo(expected.getStartIndex()))
            .satisfies(a -> assertThat(a.getEndIndex()).as("check endIndex").isEqualTo(expected.getEndIndex()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtteranceIntentUpdatableRelationshipsEquals(UtteranceIntent expected, UtteranceIntent actual) {
        assertThat(actual)
            .as("Verify UtteranceIntent relationships")
            .satisfies(a -> assertThat(a.getUtterance()).as("check utterance").isEqualTo(expected.getUtterance()))
            .satisfies(a -> assertThat(a.getIntentEntity()).as("check intentEntity").isEqualTo(expected.getIntentEntity()));
    }
}
